"use client";

import { useLocale } from "@/hooks/useLocale";

export default function ImpressumPage() {
  const { locale } = useLocale();
  const de = locale === "de";

  return (
    <div className="max-w-2xl mx-auto py-12 px-4">
      <h1 className="text-2xl font-bold text-brand mb-8">{de ? "Impressum" : "Legal Notice"}</h1>

      <div className="text-sm text-gray-700 space-y-6">
        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">{de ? "Angaben gemäß § 5 DDG" : "Information according to § 5 DDG"}</h2>
          <p className="leading-relaxed">
            superLab GmbH<br />
            Rudolf-Breitscheid-Straße 209<br />
            14482 Potsdam<br />
            {de ? "Deutschland" : "Germany"}
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">{de ? "Vertreten durch" : "Represented by"}</h2>
          <p>{de ? "Geschäftsführer" : "Managing Directors"}: Nick Bosse, Christoph Döffinger</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">{de ? "Kontakt" : "Contact"}</h2>
          <p>E-Mail: contact(at)superlab.rocks</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">{de ? "Registereintrag" : "Register Entry"}</h2>
          <p className="leading-relaxed">
            {de ? "Registergericht" : "Register Court"}: Amtsgericht Potsdam<br />
            {de ? "Registernummer" : "Register Number"}: HRB 40243 P
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">{de ? "Umsatzsteuer-ID" : "VAT ID"}</h2>
          <p>
            {de ? "USt-IdNr. gemäß § 27a UStG" : "VAT ID according to § 27a UStG"}: DE304749612
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">{de ? "Inhaltlich verantwortlich" : "Responsible for content"}</h2>
          <p className="leading-relaxed">
            {de ? "Gemäß § 18 Abs. 2 MStV" : "According to § 18 Abs. 2 MStV"}:<br />
            superLab GmbH, Rudolf-Breitscheid-Straße 209, 14482 Potsdam
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">{de ? "Projekthinweis" : "Project Notice"}</h2>
          <p className="text-gray-600 leading-relaxed">
            {de
              ? "superberater ist ein Open-Source-Projekt der superLab GmbH, veröffentlicht unter der MIT-Lizenz auf GitHub. Diese Webseite ist eine technische Live-Demo des Projekts — kein kommerzielles Produkt und kein kostenpflichtiger Dienst. Es werden keine Verträge geschlossen, keine Zahlungen erhoben und keine Beratungsleistungen erbracht. Die Ergebnisse werden von KI-Modellen Dritter generiert und können fehlerhaft sein. Keine Haftung für Entscheidungen auf Basis der Ergebnisse."
              : "superberater is an open-source project by superLab GmbH, published under the MIT License on GitHub. This website is a technical live demo of the project — not a commercial product and not a paid service. No contracts are concluded, no payments are collected, and no consulting services are provided. Results are generated by third-party AI models and may be inaccurate. No liability for decisions based on results."}
          </p>
        </section>
      </div>

      <div className="mt-12 pt-6 border-t border-gray-200 flex gap-4">
        <a href="/" className="text-sm text-brand hover:underline">← {de ? "Startseite" : "Home"}</a>
        <a href="/datenschutz" className="text-sm text-gray-500 hover:underline">{de ? "Datenschutz" : "Privacy"}</a>
      </div>
    </div>
  );
}
